---
version: '2.2'
services:
  sharelatex:
    image: sharelatex/sharelatex:chiffon-1.0
    build:
      context: .. # the root directory of the project
      dockerfile: ./src/Dockerfile
      args:
        SRC_PATH: ./src

# https://github.com/overleaf/overleaf/issues/1120#issuecomment-1623295314
  mongo:
    command: "--replSet overleaf"
  mongoinit:
    image: "${MONGO_IMAGE}"
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
        "mongo",
        "--host",
        "mongo:27017",
        "--eval",
        'rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })',
      ]
